services:
  app:
    container_name: 'viewer-for-reddit'
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - 'traefik'
    labels:
      'traefik.enable': 'true'
      'traefik.http.routers.reddit-viewer.rule': 'Host(`reddit-viewer.com`) || Host(`www.reddit-viewer.com`)'
      'traefik.http.routers.reddit-viewer.entrypoints': 'websecure'
      'traefik.http.routers.reddit-viewer.tls.certresolver': 'le'
      'traefik.http.routers.reddit-viewer.middlewares': 'hstsx,redirect-www'
      'traefik.http.services.reddit-viewer.loadbalancer.server.port': '3000'
      'traefik.http.middlewares.redirect-www.redirectregex.regex': "^https://www\\.(.+)"
      'traefik.http.middlewares.redirect-www.redirectregex.replacement': 'https://$${1}'
      'traefik.http.middlewares.redirect-www.redirectregex.permanent': 'true'

networks:
  traefik:
    external: true
