/*
 * Stamps the quicktype output as generated and checks that every expected schema exists
 * (docs/implementation.md §2.3).
 */

export const BANNER =
  "// GENERATED by `npm run types:generate` from fixtures/reddit/raw. DO NOT EDIT.\nimport 'server-only'\n"

export const REQUIRED_SCHEMAS = [
  'LinkSchema',
  'CommentSchema',
  'MoreSchema',
  'SubredditSchema',
  'AccountSchema',
  'LabeledMultiSchema',
  'MeSchema',
  'MediaMetadataItemSchema',
] as const

/** Returns the stamped source, or throws if quicktype didn't emit a required schema. */
export function stampGenerated(source: string): string {
  const missing = REQUIRED_SCHEMAS.filter((name) => !source.includes(`export const ${name} =`))
  if (missing.length > 0) {
    throw new Error(`generated.ts is missing ${missing.join(', ')}. Capture more fixtures.`)
  }
  return source.startsWith(BANNER) ? source : BANNER + source
}
