/*
 * Stamps the quicktype output as generated and checks that every expected schema exists
 * (docs/implementation.md §2.3).
 */
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const FILE = path.join(process.cwd(), 'lib', 'reddit', 'schemas', 'generated.ts')
const BANNER =
  "// GENERATED by `npm run types:generate` from fixtures/reddit/raw. DO NOT EDIT.\nimport 'server-only'\n"
const REQUIRED = [
  'LinkSchema',
  'CommentSchema',
  'MoreSchema',
  'SubredditSchema',
  'AccountSchema',
  'LabeledMultiSchema',
  'MeSchema',
]

async function main(): Promise<void> {
  let source = await readFile(FILE, 'utf8')
  if (!source.startsWith(BANNER)) source = BANNER + source

  const missing = REQUIRED.filter((name) => !source.includes(`export const ${name} =`))
  if (missing.length > 0) {
    throw new Error(`generated.ts is missing ${missing.join(', ')}. Capture more fixtures.`)
  }

  await writeFile(FILE, source)
  console.log(`generated.ts OK (${REQUIRED.length} schemas)`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exit(1)
})
